import crypto from "node:crypto";
import { z } from "zod";
export const opaque=()=>crypto.randomBytes(32).toString("base64url");
export const hash=v=>crypto.createHash("sha256").update(v).digest("hex");
export const Settings=z.object({mode:z.enum(["auto","dry_run","off"]).optional(),optimization_goal:z.enum(["balanced","quality","economy"]).optional(),send_prompt_text:z.boolean().optional()}).strict();
const Choice=z.object({task_id:z.string().regex(/^[a-f0-9]{64}$/),source:z.enum(["decisions","cache","fallback","none","single_candidate"]),reason:z.string().regex(/^[a-z_]{1,40}$/),recommended_model:z.string().regex(/^gpt-[a-z0-9.-]{1,40}$/).nullable(),recommended_effort:z.enum(["low","medium","high","xhigh","max","ultra"]).nullable(),requested_model:z.string().regex(/^gpt-[a-z0-9.-]{1,40}$/).nullable(),requested_effort:z.enum(["low","medium","high","xhigh","max","ultra"]).nullable(),effective_model:z.string().regex(/^gpt-[a-z0-9.-]{1,40}$/).nullable(),effective_effort:z.enum(["low","medium","high","xhigh","max","ultra"]).nullable(),effective_verified:z.boolean(),latency_ms:z.number().int().nonnegative(),input_tokens:z.number().int().nonnegative().nullable()}).strict();
export const Status=z.object({version:z.literal("0.3.0"),connected:z.boolean(),hook_readiness:z.enum(["untrusted","ready","unsupported","unknown"]),routing_mode:z.enum(["auto","dry_run","off"]),optimization_goal:z.enum(["balanced","quality","economy"]),recent:z.array(Choice).max(10),decisions_calls:z.number().int().nonnegative(),input_tokens:z.number().int().nonnegative().nullable(),estimated_cost_usd:z.number().nonnegative().nullable(),native_verified:z.boolean()}).strict();
export class Control {
  constructor(store,{now=Date.now}={}){this.store=store;this.now=now;}
  async startPair(){const ticket=opaque(),secret=opaque();await this.store.transaction(s=>{s.pairs[hash(ticket)]={secret:hash(secret),expires:this.now()+300000,user:null,claimed:false};});return {ticket,secret};}
  async approvePair(user,ticket){return this.store.transaction(s=>{const p=s.pairs[hash(ticket)];if(!p||p.expires<=this.now()||p.user||p.claimed)throw Error("pair_invalid");p.user=user;return true;});}
  async claimPair(ticket,secret){return this.store.transaction(s=>{const p=s.pairs[hash(ticket)];if(!p||p.expires<=this.now()||p.claimed||p.secret!==hash(secret))throw Error("pair_invalid");if(!p.user)return {pending:true};p.claimed=true;const id=crypto.randomUUID(),token=opaque();s.devices[id]={user:p.user,token:hash(token),revoked:false,status:null,last_seen:null};return {id,token};});}
  async device(token){return this.store.transaction(s=>{const found=Object.entries(s.devices).find(([,d])=>!d.revoked&&d.token===hash(token));if(!found)throw Error("device_unauthorized");return {id:found[0],user:found[1].user};});}
  async status(user){return this.store.transaction(s=>({devices:Object.entries(s.devices).filter(([,d])=>d.user===user&&!d.revoked).map(([id,d])=>({id,last_seen:d.last_seen,status:d.status})),scope:"Eligible new local subagents only",unpaired_surface:"Routing requires Gearshift Desktop on the machine running Codex"}));}
  async command(user,id,kind,payload={}){if(!["settings","connection_test","disconnect"].includes(kind))throw Error("command_invalid");const settings=kind==="settings"?Settings.parse(payload):{};return this.store.transaction(s=>{const d=s.devices[id];if(!d||d.user!==user||d.revoked)throw Error("device_not_found");const command_id=crypto.randomUUID();s.commands[command_id]={user,device:id,kind,payload:settings,expires:this.now()+60000,state:"pending"};return {command_id,expires:s.commands[command_id].expires,state:"requested"};});}
  async sync(deviceId,user,status){const valid=Status.parse(status);return this.store.transaction(s=>{const d=s.devices[deviceId];if(!d||d.user!==user||d.revoked)throw Error("device_unauthorized");d.status=valid;d.last_seen=this.now();const commands=[];for(const [id,c]of Object.entries(s.commands)){if(c.device!==deviceId||c.user!==user||c.state!=="pending")continue;if(c.expires<=this.now()){c.state="expired";continue;}c.state="claimed";commands.push({id,kind:c.kind,payload:c.payload,expires:c.expires});}return {commands};});}
  async ack(deviceId,user,id){return this.store.transaction(s=>{const c=s.commands[id];if(!c||c.device!==deviceId||c.user!==user||c.state!=="claimed")throw Error("command_invalid");c.state="completed";if(c.kind==="disconnect"){s.devices[deviceId].revoked=true;s.devices[deviceId].status=null;}return true;});}
}
