export const localPanel = String.raw`<!doctype html><html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Gearshift Desktop</title><style>:root{color-scheme:light dark}body{font:16px system-ui;max-width:720px;margin:30px auto;padding:20px}button,input,select{font:inherit;padding:9px;margin:6px}fieldset{border:1px solid #bbc;border-radius:12px;margin:16px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}#error{color:#a11}</style><h1>Gearshift Desktop</h1><p>Background routing across local Codex projects on this computer.</p><p id=summary>Loading status...</p><p><strong>Main-model routing: unavailable.</strong> <span id=adaptive>Adaptive selection: not yet verified.</span></p><fieldset><legend>Background routing</legend><label><input type=checkbox id=enabled>On</label><button id=apply>Apply</button><label>Goal <select id=goal><option>balanced</option><option>quality</option><option>economy</option></select></label><p id=settingsstate></p><details><summary>Diagnostics</summary><p>Preview makes classification requests but does not apply recommendations; it can use API credits.</p><button id=preview>Enable preview</button><button id=catalog>Refresh host catalog</button><pre id=diagnostics></pre><h3>Routing evidence</h3><pre id=status></pre></details></fieldset><fieldset><legend>API connection</legend><p>Decisions classification uses your API project. Coding stays on your Codex account.</p><form id=connect><input id=key aria-label="OpenAI API key" type=password autocomplete=off placeholder="OpenAI API key" required><button>Connect securely</button></form><button id=test>Test connection</button><button id=disconnect>Disconnect</button></fieldset><p id=error role=alert></p><h2>Why not routed</h2><pre id=reasons></pre><p>Waiting for an eligible sub-agent is normal. Gearshift does not create work or authorize delegation.</p><button id=pair>Pair with ChatGPT</button><button id=refresh>Refresh status</button><script>
const q=id=>document.getElementById(id);let dirty=false;q('enabled').onchange=q('goal').onchange=()=>dirty=true;
async function call(op,payload={}){const r=await fetch('/api/'+op,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const v=await r.json();if(!r.ok)throw Error(v.error||'operation_failed');return v}
async function refresh(){try{const s=await call('status');q('summary').textContent='Routing '+s.routing_state+'  -  '+s.routing_reason.replaceAll('_',' ');if(!dirty){q('enabled').checked=s.routing_mode==='auto';q('goal').value=s.optimization_goal;}q('adaptive').textContent=s.decisions_selection_verified?'Adaptive native selection verified.':'Adaptive selection: not yet verified.';q('settingsstate').textContent=s.settings_error?'Settings failed: '+s.settings_error:(s.settings_update||s.routing_reason==='settings_sync_pending')&&s.paired?'Settings pending local/hosted reconciliation':'Settings confirmed locally';q('reasons').textContent=Object.entries(s.passthrough_counts||{}).map(([k,v])=>k.replaceAll('_',' ')+': '+v).join('\n')||'No skipped spawns recorded';q('diagnostics').textContent=JSON.stringify(s.local_diagnostics,null,2);q('status').textContent=JSON.stringify({recent:s.recent,decisions_calls:s.decisions_calls},null,2);}catch(e){q('error').textContent=e.message}}
function action(id,fn){q(id).onclick=async()=>{q(id).disabled=true;q('error').textContent='';try{await fn();await refresh()}catch(e){q('error').textContent=e.message}finally{q(id).disabled=false}}}
action('apply',async()=>{await call('settings',{mode:q('enabled').checked?'auto':'off',optimization_goal:q('goal').value});dirty=false});action('preview',()=>call('settings',{mode:'dry_run'}));action('catalog',()=>call('refresh_catalog'));action('test',()=>call('connection_test'));action('disconnect',()=>call('disconnect'));action('refresh',refresh);
q('connect').onsubmit=async e=>{e.preventDefault();const key=q('key').value;q('key').value='';try{await call('connect',{key});await refresh()}catch(e){q('error').textContent=e.message}};
action('pair',async()=>{const w=window.open('about:blank');try{const p=await call('pair');w.location=p.url}catch(e){w.close();throw e}});refresh();setInterval(refresh,10000);
</script></html>`;
